### ISSUE TITLE
TSImport fails

### ISSUE THREAD

**Issue by shayh** [mhartington/nvim-typescript#103]
**Warning:  I will close the issue without the minimal vimrc and the reproduce ways.**
rc is based on this one https://github.com/MeirKriheli/dotneovim replacing tsuquyomi with nvim-typescript

# Problems summary
ran :TSImport on a TS angular 1 app file

## Environment Information

 * terminal: iTerm2 on mac OS Sierra 10.12.6
 * vim/nvim version:
```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_
MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstric
t-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DEC
LARATIONS -I/tmp/neovim-20171118-53412-9ielcr/neovim-0.2.2/build/config -I/tmp/neovim-20171118-53412-9ielcr/neovim-0.2.2/src -
I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -
I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20171118-53412-9ielcr/neovim-0.2.2/build/src/nvim/auto -I/tmp/neo
vim-20171118-53412-9ielcr/neovim-0.2.2/build/include
Compiled by brew@Sierra-2.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.2/share/nvim"
```

## Provide a minimal vim rc with less than 50 lines (Required!)
it all here https://github.com/MeirKriheli/dotneovim 

## Result in a python exception
```
error caught in async handler '/Users/halsbs/.config/nvim/plugged/nvim-typescript/rplugin/python3/nvim_typescript:command:TSImport []'
Traceback (most recent call last):
  File "/Users/halsbs/.config/nvim/plugged/nvim-typescript/rplugin/python3/nvim_typescript/__init__.py", line 353, in tsimport
    currentlyImportedItems = utils.getCurrentImports(self._client, self.relative_file())
  File "/Users/halsbs/.config/nvim/plugged/nvim-typescript/rplugin/python3/nvim_typescript/utils.py", line 30, in getCurrentImports
    imports = [x for x in client.getDocumentSymbols(inspectedFile)["childItems"]
TypeError: list indices must be integers or slices, not str
```

**Comment by mhartington** [comment]
I think I fixed this in a recent push today. Can you pull down and confirm?

**Comment by shayh** [comment]
thanks for the fast response, just ran PlugUpdate, the issue still occurs.
worth noting i'm using typescript 1.8.9

**Comment by mhartington** [comment]
Ahh, it could be the older version of typescript. Import has been reworked to use the server instead of a custom method for searching for imports. I should add a warning/version check for older versions.

**Comment by mhartington** [comment]
I just pushed a new version that contains some fixes/checks for older version of typescript. So It shouldn't fail when trying to import, but Im not adding back the old manual way of getting imports (as it was a pain to maintain and quite tricky to get right).  This should at least let you be able to continue working.
