### ISSUE TITLE
Completion does not work with deoplete

### ISSUE THREAD

**Issue by UnrealQuester** [mhartington/nvim-typescript#115]
# Problems summary

The completion does not appear to work with deoplete. nvim-completion-manager works just fine with this plugin and so do commands like `:TSType`.

Through some debugging I found that the `gather_candidates` method returns an empty array because an exception gets raised. It appears that the `server_handle` in the client is `None`. In fact it looks like the client created in the class is not shared with the client in `TypescriptHost` and appears to be isolated.
This is the reason commands like `:TSType` work but completion does not.

I am not familiar with building remote plugins for neovim or deoplete. Maybe there has been a change in the way deoplete initializes its sources or neovim initializes its remote plugins.

## Expected

The plugin should populate the completion menu in deoplete.

## Environment Information

 * terminal: Konsole
 * vim/nvim version: nvim v0.2.3-dev (neovim-0.2.2ubuntu2+git201802042016-0851057-f2f288d)
 
The problem is also reproducible with nvim 0.2.2

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
call plug#begin('~/.vim/plugged')
Plug 'HerringtonDarkholme/yats.vim'
Plug 'Shougo/deoplete.nvim'
Plug 'mhartington/nvim-typescript'
call plug#end()
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting

1. Start neovim and open sample file.
2. `nvim-ts: Server Started` is shown
3. Enter insert mode at the end of the file and type `bar.`
4. No completions show up

## Example file

```typescript
class asdf {
    public foo() {

    }
}

let bar = new asdf();
```

**Comment by mhartington** [comment]
Yep, this is a known issue. deoplete moved to make sources run in a separate process meaning that the client and the deoplete source are no longer in sync. Suggest for now is to pin the version of deoplete until I can get some time to rework the source/client setup. Follow this branch for further notice.

 https://github.com/mhartington/nvim-typescript/tree/singleton

**Comment by UnrealQuester** [comment]
Thanks for working on this @mhartington! Will watch out for any updates.

**Comment by Shougo** [comment]
I have added 4.0-serial tag in deoplete.
You can use it instead.

**Comment by mhartington** [comment]
Thank you @Shougo, I appreciate it.

**Comment by lambdalisue** [comment]
https://github.com/Shougo/deoplete.nvim/issues/638

With `4.0-serial`, nvim-typescript works fine 👍

**Comment by Shougo** [comment]
I have impmented the serial completion support.

**Comment by UnrealQuester** [comment]
Can confirm that setting `deoplete#num_processes = 1` works with the latest master.

@mhartington do you want to keep this issue open for the `singleton` branch?

**Comment by mhartington** [comment]
@UnrealQuester Yes, I'll keep this open until I get proper support for the multiple-processes

**Comment by mhartington** [comment]
Just to provide an update. This is a bit more difficult than I had expected. 
I had attempted some work using Sockets, to communicate between the deoplete source and the typescript server instance, but this ends up blocking the rest of nvim from starting up. 

Im welcoming any other ideas/suggestions at the moment, as I'm a bit out of my element here. Not sure what the best approach is here.

**Comment by mhartington** [comment]
Update: I think I have things working finally with the mutli-process support.

If you could test branch `singleton` and report back any issues, that would help. Also run `UpdateRemotePlugins` to get updates to new functions.

**Comment by UnrealQuester** [comment]
@mhartington The completions now somewhat work with multiple deoplete processes.
I get the correct list of completions sometimes, but not always.
Using the example file from the first post, typing `bar.` shows the function in the completion menu. Pressing backspace and typing `.` again now only shows `__dirname` as the completion option. The master branch with only one process in the deoplete options works as expected.

**Comment by mhartington** [comment]
Yeah, I'm seeing that too. Going to dig more into it and see what's causing it.

**Comment by mhartington** [comment]
@UnrealQuester I have fixed the completion issues and it's now working well.
Plus, still non-blocking.


![completion-fix](https://user-images.githubusercontent.com/2835826/36559490-36390788-17dc-11e8-8e3f-5a3c353a8eb6.gif)

**Comment by UnrealQuester** [comment]
@mhartington It works! Could not find any problems during testing.
Thanks for the hard work you put into this!

**Comment by paldepind** [comment]
Has this been fixed on master? It looks like this still some unmerged stuff on the `singleton` branch.

**Comment by kreedz** [comment]
I don't see it on master too and can't actually use singleton branch, because some Windows issues was fixed recently on master.

**Comment by mhartington** [comment]
@paldepind  and @kreedz yes, this has merged into master via https://github.com/mhartington/nvim-typescript/commit/6c67a845c98306f4b1adfd18aa80fb0255901a1f

**Comment by l5x** [comment]
I think it still doesn't work without the `deoplete#num_processes = 1`
